version: "3.4"
services:
  app:
    build:
      context: .
    environment:
      SSH_GEN_CLIENT_KEY: "true"
    volumes:
    - "./examples/data/ssh_key:/root/.ssh/id_rsa" 
    ports:
    - "2222:22"
    - "12345:12345"
